In [1]:
print("hello ! I am on GITHUB")

hello ! I am on GITHUB


In [4]:
dict = {
           "name" : pd.Series(["A", "B", "c"]), 
           "age": pd.Series([21, 22, 23]), 
           "salary": pd.Series([11.5, 23.4, 56]),
           "working" : pd.Series([True, False, True])
       }
dict

{'name': 0    A
 1    B
 2    c
 dtype: object,
 'age': 0    21
 1    22
 2    23
 dtype: int64,
 'salary': 0    11.5
 1    23.4
 2    56.0
 dtype: float64,
 'working': 0     True
 1    False
 2     True
 dtype: bool}

In [3]:
import pandas as pd

In [5]:
data_frame = pd.DataFrame(dict)
data_frame

name  age  salary  working
0    A   21    11.5     True
1    B   22    23.4    False
2    c   23    56.0     True

In [6]:
print("Type of data frame object : ", type(data_frame))
print("Data types of data frame columns : ", data_frame.dtypes)
print("Columns of data frame : ", data_frame.columns)
print("Row labels of data frame : ", data_frame.index)
print("Number of entries in data frame : ", len(data_frame))
print("Number of cells is data frame : " , data_frame.size)
print()

Type of data frame object :  <class 'pandas.core.frame.DataFrame'>
Data types of data frame columns :  name        object
age          int64
salary     float64
working       bool
dtype: object
Columns of data frame :  Index(['name', 'age', 'salary', 'working'], dtype='object')
Row labels of data frame :  RangeIndex(start=0, stop=3, step=1)
Number of entries in data frame :  3
Number of cells is data frame :  12



In [7]:
dict = { 
            "one" : pd.Series(['A', 'B', 'C', 'D'], index=["a", "b", "c", "d"]), 
            "two" : pd.Series([1, 2, 3], index=["a", "b", "c"]),
            "three " : pd.Series([11, 22], index=["a", "b"])
       }
dict

{'one': a    A
 b    B
 c    C
 d    D
 dtype: object,
 'two': a    1
 b    2
 c    3
 dtype: int64,
 'three ': a    11
 b    22
 dtype: int64}

In [8]:
data_frame = pd.DataFrame(dict)
data_frame

one  two  three 
a   A  1.0    11.0
b   B  2.0    22.0
c   C  3.0     NaN
d   D  NaN     NaN

In [11]:
array = np.random.randint(5, size = 5)
array

array([4, 4, 1, 4, 1])

In [10]:
import numpy as np

In [12]:
list1 = [ i*i for i in range(5)]
list1

[0, 1, 4, 9, 16]

In [13]:
dict = {
            "column1" : array,
            "column2" : list1
       }
dict

{'column1': array([4, 4, 1, 4, 1]), 'column2': [0, 1, 4, 9, 16]}

In [14]:
data_frame = pd.DataFrame(dict)
data_frame

column1  column2
0        4        0
1        4        1
2        1        4
3        4        9
4        1       16

In [15]:
#Create an index that will be used along with each series
list_of_indices = ["index1", "index2", "index3", "index4", "index5"]

In [16]:
#Create a serieses using the data values for a column with index specified
series1 = pd.Series([1, 2, 3, 4, 5], index = list_of_indices)
series2 = pd.Series([11, 22, 33, 44, 55], index = list_of_indices)
series3 = pd.Series(["A", "B", "C", "D", "E"], index = list_of_indices)

In [17]:
#Create a list of serieses
list_of_series = [ series1, series2, series3]

In [18]:
#Use pd.concat along horizontal axis to add the series to the data frames
data_frame = pd.concat(list_of_series, axis=1)
data_frame

0   1  2
index1  1  11  A
index2  2  22  B
index3  3  33  C
index4  4  44  D
index5  5  55  E

In [19]:
#Rename the data frames columns
list_of_columns = ["column1", "column2", "column3"]
data_frame.columns = list_of_columns
data_frame

column1  column2 column3
index1        1       11       A
index2        2       22       B
index3        3       33       C
index4        4       44       D
index5        5       55       E

In [20]:
#Create an index that will be used along with each series
list_of_indices = ["column1", "column2", "column3", "column4", "column5"]

In [21]:
#Create a serieses using the data values for a column with index specified
series1 = pd.Series([1, 2, "A", True, 5.0], index = list_of_indices)
series2 = pd.Series([11, 22, "B", False, 55.0], index = list_of_indices)
series3 = pd.Series([21, 34, "C", True, 12], index = list_of_indices)

In [22]:
#Create a list of serieses
list_of_series = [ series1, series2, series3]

In [23]:
#Use pd.DataFrame along horizontal axis to add the series to the data frames
data_frame = pd.DataFrame(list_of_series)
data_frame

column1  column2 column3  column4  column5
0        1        2       A     True      5.0
1       11       22       B    False     55.0
2       21       34       C     True     12.0

Q1. Create a DataFrame by passing a NumPy array, with a datetime index and labeled columns.

In [25]:
dt_index = pd.date_range("20190701",periods=5)
dt_index

DatetimeIndex(['2019-07-01', '2019-07-02', '2019-07-03', '2019-07-04',
               '2019-07-05'],
              dtype='datetime64[ns]', freq='D')

In [27]:
print("Date index : \n", dt_index)

Date index : 
 DatetimeIndex(['2019-07-01', '2019-07-02', '2019-07-03', '2019-07-04',
               '2019-07-05'],
              dtype='datetime64[ns]', freq='D')


In [30]:
array = np.random.random((5,4))

In [31]:
print("Array : \n",array)

Array : 
 [[0.29574296 0.94940303 0.69225986 0.20420189]
 [0.78865786 0.03032002 0.91207884 0.52981064]
 [0.12866562 0.20281234 0.6221217  0.50879077]
 [0.72926456 0.7319549  0.41730333 0.04573199]
 [0.20915324 0.15925809 0.77427091 0.77306547]]


In [32]:
list_of_columns = ["column1","Column2","column3","column4"]

In [36]:
data_frame = pd.DataFrame(array,index=dt_index,columns=list_of_columns)
data_frame

column1   Column2   column3   column4
2019-07-01  0.295743  0.949403  0.692260  0.204202
2019-07-02  0.788658  0.030320  0.912079  0.529811
2019-07-03  0.128666  0.202812  0.622122  0.508791
2019-07-04  0.729265  0.731955  0.417303  0.045732
2019-07-05  0.209153  0.159258  0.774271  0.773065